num.partitions=3
default.replication.factor=3
transaction.state.log.min.isr=2
process.roles=broker,controller
controller.listener.names=CONTROLLER
controller.quorum.voters=1@$CLIENT_IP:19093,2@$CLIENT_IP:29093,3@$CLIENT_IP:39093
auto.create.topics.enable=true
node.id=1
advertised.listeners=PLAINTEXT://$CLIENT_IP:19092
log.retention.hours=72
min.insync.replicas=2
transaction.state.log.replication.factor=3
listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
zookeeper.connect=
log.dirs=/var/lib/kafka/data
offsets.topic.replication.factor=3
