port 26379
protected-mode no
bind 0.0.0.0
sentinel resolve-hostnames yes
sentinel monitor valkey-master $CLIENT_IP 16379 2
sentinel auth-pass valkey-master valkeypass
sentinel down-after-milliseconds valkey-master 5000
sentinel failover-timeout valkey-master 10000
sentinel parallel-syncs valkey-master 1

sentinel announce-ip $CLIENT_IP
sentinel announce-port 26380
