appendonly yes
appendfilename "appendonly.aof"
requirepass valkeypass
masterauth valkeypass
bind 0.0.0.0
protected-mode no
replicaof valkey-1 6379
replica-announce-ip $CLIENT_IP
replica-announce-port 16381
